INSERT INTO Users (Username, PW) VALUES ('Joe', 'Mama');

INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Bam Adebayo', '27', 'Miami Heat', '78', '1113', '540', '79', '221', '251', '328', '749', '337', '98', '53', '161', '1410');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Ochai Agbaji', '24', 'Toronto Raptors', '64', '534', '266', '101', '253', '34', '48', '242', '98', '58', '30', '54', '667');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Nickeil Alexander-Walker', '26', 'Minnesota Timberwolves', '82', '616', '270', '141', '370', '92', '118', '265', '223', '50', '34', '99', '773');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jarrett Allen', '27', 'Cleveland Cavaliers', '82', '640', '452', '0', '5', '199', '277', '798', '158', '77', '73', '97', '1103');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Harrison Barnes', '32', 'San Antonio Spurs', '82', '683', '347', '156', '360', '161', '199', '310', '136', '39', '14', '50', '1011');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Scottie Barnes', '23', 'Toronto Raptors', '65', '1063', '474', '76', '280', '228', '302', '502', '378', '93', '63', '185', '1252');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('RJ Barrett', '24', 'Toronto Raptors', '58', '982', '460', '107', '306', '196', '311', '366', '314', '46', '17', '165', '1223');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jamison Battle', '23', 'Toronto Raptors', '59', '347', '149', '105', '259', '16', '18', '158', '53', '17', '10', '27', '419');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Nicolas Batum', '36', 'Los Angeles Clippers', '78', '238', '104', '88', '203', '17', '21', '218', '84', '52', '36', '34', '313');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Malik Beasley', '28', 'Detroit Pistons', '82', '1071', '461', '319', '766', '95', '140', '214', '139', '73', '5', '83', '1336');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Anthony Black', '21', 'Orlando Magic', '78', '620', '262', '62', '195', '150', '197', '230', '240', '86', '48', '139', '736');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Chris Boucher', '32', 'Toronto Raptors', '50', '370', '182', '70', '193', '68', '87', '224', '33', '24', '25', '29', '502');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Christian Braun', '24', 'Denver Nuggets', '79', '821', '476', '89', '224', '177', '214', '410', '205', '85', '37', '81', '1218');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Mikal Bridges', '28', 'New York Knicks', '82', '1183', '592', '164', '463', '96', '118', '259', '306', '75', '43', '132', '1444');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Bruce Brown', '28', 'Toronto Raptors', '18', '131', '57', '11', '36', '26', '29', '68', '28', '17', '3', '19', '151');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Matas Buzelis', '20', 'Chicago Bulls', '80', '555', '252', '96', '266', '88', '108', '278', '79', '29', '75', '74', '688');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Kentavious Caldwell-Pope', '32', 'Orlando Magic', '77', '544', '239', '113', '330', '82', '95', '169', '136', '99', '34', '62', '673');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Toumani Camara', '24', 'Portland Trail Blazers', '78', '716', '328', '135', '360', '91', '126', '450', '175', '116', '50', '109', '882');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Bub Carrington', '19', 'Washington Wizards', '82', '748', '300', '138', '407', '69', '85', '341', '364', '54', '21', '141', '807');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('D.J. Carton', '24', 'Toronto Raptors', '4', '7', '1', '0', '3', '1', '1', '4', '3', '2', '0', '4', '3');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Stephon Castle', '20', 'San Antonio Spurs', '81', '988', '423', '95', '333', '249', '344', '297', '332', '74', '22', '177', '1190');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Colin Castleton', '24', 'Toronto Raptors', '11', '64', '32', '2', '8', '13', '18', '76', '18', '6', '8', '21', '79');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Julian Champagnie', '23', 'San Antonio Spurs', '82', '665', '276', '178', '480', '85', '94', '318', '111', '61', '35', '74', '815');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Ulrich Chomche', '19', 'Toronto Raptors', '7', '5', '2', '0', '0', '1', '2', '8', '2', '0', '1', '2', '5');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Max Christie', '22', 'TOT', '78', '590', '252', '115', '314', '130', '152', '258', '146', '64', '31', '88', '749');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Dyson Daniels', '22', 'Atlanta Hawks', '76', '923', '455', '80', '235', '83', '140', '449', '333', '229', '55', '155', '1073');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('DeMar DeRozan', '35', 'Sacramento Kings', '77', '1308', '624', '84', '256', '378', '441', '298', '342', '62', '32', '105', '1710');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Gradey Dick', '21', 'Toronto Raptors', '54', '647', '265', '114', '326', '133', '155', '193', '98', '48', '10', '83', '777');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Spencer Dinwiddie', '32', 'Dallas Mavericks', '79', '682', '284', '109', '326', '195', '243', '209', '349', '70', '17', '102', '872');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jalen Duren', '21', 'Detroit Pistons', '78', '546', '378', '0', '0', '162', '242', '807', '209', '54', '89', '136', '918');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Anthony Edwards', '23', 'Minnesota Timberwolves', '79', '1612', '721', '320', '811', '415', '496', '450', '359', '91', '51', '249', '2177');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Keon Ellis', '25', 'Sacramento Kings', '80', '464', '227', '139', '321', '73', '86', '212', '120', '121', '63', '71', '666');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Bruno Fernando', '26', 'Toronto Raptors', '17', '49', '26', '0', '0', '6', '8', '51', '18', '4', '9', '14', '58');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Shai Gilgeous-Alexander', '26', 'Oklahoma City Thunder', '76', '1656', '860', '163', '435', '601', '669', '379', '486', '131', '77', '183', '2484');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jalen Green', '23', 'Houston Rockets', '82', '1437', '608', '234', '661', '273', '336', '377', '282', '71', '27', '203', '1723');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Tim Hardaway Jr.', '33', 'Detroit Pistons', '77', '680', '276', '168', '457', '124', '145', '183', '123', '38', '7', '48', '844');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('James Harden', '35', 'Los Angeles Clippers', '79', '1295', '531', '235', '668', '505', '578', '456', '687', '118', '55', '341', '1802');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Josh Hart', '30', 'New York Knicks', '77', '770', '404', '84', '252', '159', '205', '737', '453', '119', '27', '158', '1051');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Tyler Herro', '25', 'Miami Heat', '77', '1378', '651', '251', '670', '287', '327', '399', '424', '69', '17', '198', '1840');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Buddy Hield', '32', 'Golden State Warriors', '82', '786', '328', '203', '549', '53', '64', '264', '134', '69', '23', '91', '912');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Ronald Holland II', '19', 'Detroit Pistons', '81', '416', '197', '36', '151', '92', '122', '218', '82', '49', '17', '72', '522');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Keldon Johnson', '25', 'San Antonio Spurs', '77', '770', '371', '87', '274', '150', '194', '371', '125', '49', '22', '77', '979');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Keon Johnson', '23', 'Brooklyn Nets', '79', '779', '303', '126', '401', '107', '139', '297', '175', '82', '30', '116', '839');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Tyus Jones', '28', 'PHX', '81', '683', '306', '166', '401', '51', '57', '196', '429', '69', '8', '91', '829');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Derrick Jones Jr.', '28', 'Los Angeles Clippers', '77', '589', '310', '78', '219', '83', '118', '263', '60', '79', '33', '66', '781');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Dalton Knecht', '24', 'Los Angeles Lakers', '78', '557', '257', '128', '340', '64', '84', '216', '66', '24', '8', '37', '706');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('A.J. Lawson', '24', 'Toronto Raptors', '26', '190', '80', '33', '101', '43', '63', '86', '31', '13', '6', '15', '236');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Kevon Looney', '29', 'Golden State Warriors', '76', '278', '143', '2', '5', '56', '99', '462', '118', '46', '37', '39', '344');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Brook Lopez', '37', 'Milwaukee Bucks', '80', '774', '394', '139', '373', '114', '138', '401', '143', '50', '148', '84', '1041');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('T.J. McConnell', '33', 'Indiana Pacers', '79', '624', '324', '15', '49', '57', '77', '193', '351', '83', '21', '109', '720');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jaden McDaniels', '24', 'Minnesota Timberwolves', '82', '834', '398', '100', '303', '104', '128', '470', '163', '110', '74', '95', '1000');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Davion Mitchell', '26', 'Toronto Raptors', '44', '244', '106', '42', '117', '25', '37', '85', '203', '31', '8', '78', '279');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jonathan Mogbo', '23', 'Toronto Raptors', '63', '356', '156', '17', '70', '60', '82', '311', '146', '55', '34', '70', '389');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Keegan Murray', '24', 'Sacramento Kings', '76', '820', '364', '154', '449', '60', '72', '507', '109', '61', '69', '60', '942');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Georges Niang', '31', 'TOT', '79', '620', '286', '166', '409', '46', '58', '272', '111', '28', '14', '82', '784');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Kelly Olynyk', '34', 'Toronto Raptors', '24', '118', '59', '19', '43', '34', '43', '89', '56', '16', '8', '35', '171');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Chris Paul', '39', 'San Antonio Spurs', '82', '583', '249', '140', '371', '85', '92', '296', '605', '103', '22', '129', '723');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Julian Phillips', '21', 'Chicago Bulls', '79', '287', '128', '50', '153', '60', '76', '169', '39', '38', '20', '27', '366');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Scotty Pippen Jr.', '24', 'Memphis Grizzlies', '79', '594', '285', '87', '219', '122', '171', '259', '347', '103', '30', '138', '779');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jakob Poeltl', '29', 'Toronto Raptors', '57', '579', '363', '1', '3', '97', '144', '547', '158', '66', '71', '111', '824');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Michael Porter Jr.', '26', 'Denver Nuggets', '77', '1048', '528', '193', '489', '149', '194', '540', '165', '50', '38', '104', '1398');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Taurean Prince', '31', 'Milwaukee Bucks', '80', '514', '235', '147', '335', '39', '48', '287', '155', '76', '15', '82', '656');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Payton Pritchard', '27', 'Boston Celtics', '80', '866', '409', '255', '626', '71', '84', '307', '279', '70', '14', '83', '1144');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Immanuel Quickley', '25', 'Toronto Raptors', '33', '438', '184', '85', '225', '111', '128', '117', '191', '23', '4', '58', '564');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Naz Reid', '25', 'Minnesota Timberwolves', '80', '923', '426', '175', '462', '111', '143', '480', '181', '58', '72', '108', '1138');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jared Rhoden', '25', 'Toronto Raptors', '10', '79', '40', '12', '37', '22', '25', '38', '14', '9', '2', '8', '114');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Orlando Robinson', '24', 'Toronto Raptors', '35', '244', '109', '16', '47', '50', '63', '206', '68', '14', '15', '45', '284');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Alperen Sengun', '22', 'Houston Rockets', '76', '1143', '567', '21', '90', '296', '428', '786', '372', '84', '61', '194', '1451');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jamal Shead', '22', 'Toronto Raptors', '75', '504', '204', '72', '223', '53', '69', '115', '316', '58', '10', '117', '533');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Pascal Siakam', '31', 'Indiana Pacers', '78', '1182', '613', '126', '324', '226', '308', '540', '263', '70', '42', '109', '1578');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Cole Swider', '25', 'Toronto Raptors', '8', '58', '22', '15', '42', '0', '1', '25', '2', '4', '2', '4', '59');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Garrett Temple', '38', 'Toronto Raptors', '28', '60', '18', '6', '28', '11', '12', '29', '31', '17', '2', '10', '53');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Obi Toppin', '27', 'Indiana Pacers', '79', '599', '317', '110', '301', '89', '114', '318', '128', '46', '28', '68', '833');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jonas Valančiūnas', '32', 'TOT', '81', '627', '345', '8', '37', '145', '165', '627', '164', '37', '46', '120', '843');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Ja''Kobe Walter', '20', 'Toronto Raptors', '52', '393', '159', '65', '186', '66', '83', '160', '81', '43', '10', '50', '449');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jaylen Wells', '21', 'Memphis Grizzlies', '79', '676', '287', '138', '392', '111', '135', '268', '135', '44', '8', '69', '823');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Derrick White', '30', 'Boston Celtics', '76', '959', '424', '265', '691', '135', '161', '341', '361', '72', '80', '131', '1248');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Aaron Wiggins', '26', 'Oklahoma City Thunder', '76', '728', '355', '130', '339', '74', '89', '295', '134', '60', '18', '69', '914');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Jalen Wilson', '24', 'Brooklyn Nets', '79', '620', '246', '122', '362', '135', '165', '270', '145', '40', '5', '79', '749');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Trae Young', '26', 'Atlanta Hawks', '76', '1376', '566', '218', '642', '491', '561', '236', '880', '91', '12', '355', '1841');
INSERT INTO Player (PName, PlayerAge, TeamName, GamesPlayed, FieldGoalAttempt, FieldGoalMade, ThreePointMade, ThreePointAttempt, FreeThrowMade, FreeThrowAttempt, Rebounds, Assists, Steals, Blocks, Turnovers, Points) VALUES ('Ivica Zubac', '28', 'Los Angeles Clippers', '80', '942', '592', '0', '0', '156', '236', '1010', '214', '55', '90', '127', '1340');

INSERT INTO Users (Username, PW) Values
('admin', 'admin'),
('user1', 'password1'),
('user2', 'password2'),
('user3', 'password3'),
('user4', 'password4'),
('user5', 'password5'),
('user6', 'password6'),
('user7', 'password7'),
('user8', 'password8'),
('user9', 'password9'),
('user10', 'password10');