
INSERT INTO Questions (AuthorID, QuestionText, QuestionType) VALUES
(1, 'Who scored the most total points in the 2024–2025 regular season?', 'player'),
(1, 'Who led the league in points per game in 2024–2025?', 'player'),
(1, 'Who had the most total rebounds in 2024–2025?', 'player'),
(1, 'Who averaged the most rebounds per game in 2024–2025?', 'player'),
(1, 'Who recorded the most total assists in 2024–2025?', 'player'),
(1, 'Who averaged the most assists per game in 2024–2025?', 'player'),
(1, 'Who recorded the most triple-doubles in 2024–2025?', 'player'),
(1, 'Who averaged the most steals per game in 2024–2025?', 'player'),
(1, 'Who averaged the most blocks per game in 2024–2025?', 'player'),
(1, 'Who had the highest free-throw percentage (qualifying) in 2024–2025?', 'player'),
(1, 'Who had the highest field-goal percentage (qualifying) in 2024–2025?', 'player'),
(1, 'Who had the highest 3-point percentage (qualifying) in 2024–2025?', 'player'),
(1, 'Who averaged the most minutes per game in 2024–2025?', 'player'),
(1, 'Who averaged the most turnovers per game in 2024–2025?', 'player'),
(1, 'Who recorded the most double-doubles in 2024–2025?', 'player'),
(1, 'Who was named MVP of the 2024–2025 NBA season?', 'player'),
(1, 'Who had the most 50-point games in 2024–2025?', 'player'),
(1, 'Who had the most triple-doubles in the 2025 playoffs?', 'player'),
(1, 'Who became the first Canadian to lead the NBA in scoring?', 'player'),
(1, 'Who had the longest streak of 20-point games in 2024–2025?', 'player');

INSERT INTO Answers (QuestionID, AnswerNumber, ResponseText, IsCorrect) VALUES
(1, 1, 'Shai Gilgeous-Alexander', TRUE), (1, 2, 'Nikola Jokić', FALSE), (1, 3, 'Giannis Antetokounmpo', FALSE), (1, 4, 'Anthony Edwards', FALSE),
(2, 1, 'Shai Gilgeous-Alexander', TRUE), (2, 2, 'Giannis Antetokounmpo', FALSE), (2, 3, 'Luka Dončić', FALSE), (2, 4, 'Donovan Mitchell', FALSE),
(3, 1, 'Domantas Sabonis', TRUE), (3, 2, 'Giannis Antetokounmpo', FALSE), (3, 3, 'Nikola Jokić', FALSE), (3, 4, 'Alperen Şengün', FALSE),
(4, 1, 'Domantas Sabonis', TRUE), (4, 2, 'Nikola Jokić', FALSE), (4, 3, 'Karl-Anthony Towns', FALSE), (4, 4, 'Jayson Tatum', FALSE),
(5, 1, 'Tyrese Haliburton', TRUE), (5, 2, 'Nikola Jokić', FALSE), (5, 3, 'Shai Gilgeous-Alexander', FALSE), (5, 4, 'James Harden', FALSE),
(6, 1, 'Trae Young', TRUE), (6, 2, 'Tyrese Haliburton', FALSE), (6, 3, 'Nikola Jokić', FALSE), (6, 4, 'James Harden', FALSE),
(7, 1, 'Nikola Jokić', TRUE), (7, 2, 'Giannis Antetokounmpo', FALSE), (7, 3, 'LeBron James', FALSE), (7, 4, 'Domantas Sabonis', FALSE),
(8, 1, 'Dyson Daniels', TRUE), (8, 2, 'Jayson Tatum', FALSE), (8, 3, 'LeBron James', FALSE), (8, 4, 'Nikola Jokić', FALSE),
(9, 1, 'Victor Wembanyama', TRUE), (9, 2, 'Myles Turner', FALSE), (9, 3, 'Isaiah Stewart', FALSE), (9, 4, 'Chet Holmgren', FALSE),
(10, 1, 'Stephen Curry', TRUE), (10, 2, 'Jarrett Allen', FALSE), (10, 3, 'Seth Curry', FALSE), (10, 4, 'Kevin Durant', FALSE),
(11, 1, 'Jarrett Allen', TRUE), (11, 2, 'Nikola Jokić', FALSE), (11, 3, 'Victor Wembanyama', FALSE), (11, 4, 'Stephen Curry', FALSE),
(12, 1, 'Seth Curry', TRUE), (12, 2, 'Stephen Curry', FALSE), (12, 3, 'Derrick White', FALSE), (12, 4, 'Jayson Tatum', FALSE),
(13, 1, 'Josh Hart', TRUE), (13, 2, 'Cade Cunningham', FALSE), (13, 3, 'LeBron James', FALSE), (13, 4, 'Luka Dončić', FALSE),
(14, 1, 'Trae Young', TRUE), (14, 2, 'Shai Gilgeous-Alexander', FALSE), (14, 3, 'Nikola Jokić', FALSE), (14, 4, 'James Harden', FALSE),
(15, 1, 'Domantas Sabonis', TRUE), (15, 2, 'Nikola Jokić', FALSE), (15, 3, 'Giannis Antetokounmpo', FALSE), (15, 4, 'Jayson Tatum', FALSE),
(16, 1, 'Shai Gilgeous-Alexander', TRUE), (16, 2, 'Nikola Jokić', FALSE), (16, 3, 'Giannis Antetokounmpo', FALSE), (16, 4, 'Luka Dončić', FALSE),
(17, 1, 'Shai Gilgeous-Alexander', TRUE), (17, 2, 'Kevin Durant', FALSE), (17, 3, 'Luka Dončić', FALSE), (17, 4, 'Devin Booker', FALSE),
(18, 1, 'Nikola Jokić', TRUE), (18, 2, 'Giannis Antetokounmpo', FALSE), (18, 3, 'Tyrese Haliburton', FALSE), (18, 4, 'Josh Hart', FALSE),
(19, 1, 'Shai Gilgeous-Alexander', TRUE), (19, 2, 'Andrew Wiggins', FALSE), (19, 3, 'Kelly Olynyk', FALSE), (19, 4, 'Jamal Murray', FALSE),
(20, 1, 'Shai Gilgeous-Alexander', TRUE), (20, 2, 'Kevin Durant', FALSE), (20, 3, 'Luka Dončić', FALSE), (20, 4, 'Michael Jordan', FALSE);