INSERT INTO Teams (TeamID, TeamName) VALUES ('0' ,'Atlanta Hawks');
INSERT INTO Teams (TeamID, TeamName) VALUES ('1' ,'Boston Celtics');
INSERT INTO Teams (TeamID, TeamName) VALUES ('2' ,'Brooklyn Nets');
INSERT INTO Teams (TeamID, TeamName) VALUES ('3' ,'Charlotte Hornets');
INSERT INTO Teams (TeamID, TeamName) VALUES ('4' ,'Chicago Bulls');
INSERT INTO Teams (TeamID, TeamName) VALUES ('5' ,'Cleveland Cavaliers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('6' ,'Dallas Mavericks');
INSERT INTO Teams (TeamID, TeamName) VALUES ('7' ,'Denver Nuggets');
INSERT INTO Teams (TeamID, TeamName) VALUES ('8' ,'Detroit Pistons');
INSERT INTO Teams (TeamID, TeamName) VALUES ('9' ,'Golden State Warriors');
INSERT INTO Teams (TeamID, TeamName) VALUES ('10' ,'Houston Rockets');
INSERT INTO Teams (TeamID, TeamName) VALUES ('11' ,'Indiana Pacers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('12' ,'Los Angeles Clippers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('13' ,'Los Angeles Lakers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('14' ,'Memphis Grizzlies');
INSERT INTO Teams (TeamID, TeamName) VALUES ('15' ,'Miami Heat');
INSERT INTO Teams (TeamID, TeamName) VALUES ('16' ,'Milwaukee Bucks');
INSERT INTO Teams (TeamID, TeamName) VALUES ('17' ,'Minnesota Timberwolves');
INSERT INTO Teams (TeamID, TeamName) VALUES ('18' ,'New Orleans Pelicans');
INSERT INTO Teams (TeamID, TeamName) VALUES ('19' ,'New York Knicks');
INSERT INTO Teams (TeamID, TeamName) VALUES ('20' ,'Oklahoma City Thunder');
INSERT INTO Teams (TeamID, TeamName) VALUES ('21' ,'Orlando Magic');
INSERT INTO Teams (TeamID, TeamName) VALUES ('22' ,'Philadelphia 76ers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('23' ,'Phoenix Suns');
INSERT INTO Teams (TeamID, TeamName) VALUES ('24' ,'Portland Trail Blazers');
INSERT INTO Teams (TeamID, TeamName) VALUES ('25' ,'Sacramento Kings');
INSERT INTO Teams (TeamID, TeamName) VALUES ('26' ,'San Antonio Spurs');
INSERT INTO Teams (TeamID, TeamName) VALUES ('27' ,'Toronto Raptors');
INSERT INTO Teams (TeamID, TeamName) VALUES ('28' ,'Utah Jazz');
INSERT INTO Teams (TeamID, TeamName) VALUES ('29' ,'Washington Wizards');
