SELECT PlayerID, PName
FROM ALL_PLAYER_INFO
WHERE {{STAT1}} >= (
    SELECT {{STAT1}} FROM ALL_PLAYER_INFO WHERE PName = '{{PLAYER1}}'
)
INTERSECT
SELECT PlayerID, PName
FROM ALL_PLAYER_INFO
WHERE {{STAT2}} >= (
    SELECT {{STAT2}} FROM ALL_PLAYER_INFO WHERE PName = '{{PLAYER2}}'
);
